"""Add CheckoutHistory audit trail

Revision ID: d20771c3bb27
Revises: f2762a85d4db
Create Date: 2026-02-01 21:05:22.640532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20771c3bb27'
down_revision = 'f2762a85d4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id_number', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkout_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkout_history_tool_id_number'), ['tool_id_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkout_history_username'), ['username'], unique=False)
    # tools and user already exist from initial migration - removed duplicate
    """
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id_number', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('tool_location', sa.String(length=64), nullable=False),
    sa.Column('tool_status', sa.String(length=64), nullable=False),
    sa.Column('tool_calibration_due', sa.String(length=64), nullable=False),
    sa.Column('tool_calibration_date', sa.String(length=64), nullable=False),
    sa.Column('tool_calibration_cert', sa.String(length=64), nullable=False),
    sa.Column('tool_calibration_schedule', sa.String(length=64), nullable=False),
    sa.Column('checked_out_by', sa.String(length=128), nullable=True),
    sa.Column('checkout_time', sa.DateTime(), nullable=True),
    sa.Column('checkin_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('badge_id', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('supervisor_username', sa.String(length=64), nullable=False),
    sa.Column('supervisor_email', sa.String(length=80), nullable=False),
    sa.Column('supervisor_phone', sa.String(length=10), nullable=False),
    sa.Column('manager_username', sa.String(length=64), nullable=True),
    sa.Column('manager_email', sa.String(length=80), nullable=True),
    sa.Column('manager_phone', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_badge_id'), ['badge_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_manager_email'), ['manager_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_manager_phone'), ['manager_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_manager_username'), ['manager_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_supervisor_email'), ['supervisor_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_supervisor_phone'), ['supervisor_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_supervisor_username'), ['supervisor_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
    """
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkout_history_username'))
        batch_op.drop_index(batch_op.f('ix_checkout_history_tool_id_number'))

    op.drop_table('checkout_history')
    # ### end Alembic commands ###
