#!/usr/bin/env bash
# Sets HOST_UID / HOST_GID for docker-compose `user:` lines so bind-mounted volumes
# are written as the deploy user (e.g. ansible), not root.
#
# Source from deploy scripts, then call write_compose_host_user_env "$APP_ROOT".
# That writes .env.compose-host-user; pass it as extra --env-file to docker compose
# so values survive `sudo docker compose` (sudo does not forward caller env by default).
#
# Override: export HOST_UID=1001 HOST_GID=1001 before sourcing.
# If this script runs as root (e.g. sudo -i), IDs fall back to the ansible account when present.

_u="$(id -u)"
_g="$(id -g)"
if [ "$_u" = "0" ] && id -u ansible &>/dev/null; then
  _u="$(id -u ansible)"
  _g="$(id -g ansible)"
fi
: "${HOST_UID:=$_u}"
: "${HOST_GID:=$_g}"
export HOST_UID HOST_GID

write_compose_host_user_env() {
  local root="$1"
  if [ -z "$root" ] || [ ! -d "$root" ]; then
    echo "write_compose_host_user_env: need existing APP_ROOT directory" >&2
    return 1
  fi
  local out="$root/.env.compose-host-user"
  umask 077
  {
    echo "# Generated by scripts/export_compose_uid_gid.sh — container user: for compose bind mounts"
    echo "HOST_UID=$HOST_UID"
    echo "HOST_GID=$HOST_GID"
  } >"$out"
}
